version: 0.2

phases:
  pre_build:
    commands:
      - env
      - echo Logging in to Amazon ECR...            
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...                
      - docker build -t php-load-test:latest .
      - docker tag php-load-test:latest 069554186194.dkr.ecr.ap-southeast-1.amazonaws.com/mywebsite:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 069554186194.dkr.ecr.ap-southeast-1.amazonaws.com/mywebsite:latest
