version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...      
      #aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 069554186194.dkr.ecr.ap-southeast-1.amazonaws.com
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build php-load-test:latest .
      - docker tag php-load-test:latest 069554186194.dkr.ecr.ap-southeast-1.amazonaws.com/mywebsite:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 069554186194.dkr.ecr.ap-southeast-1.amazonaws.com/mywebsite:latest
