version: 0.2

phases:
  pre_build:
    commands:
      - env
      - echo Logging in to Amazon ECR...            
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`            
      #- docker build -t php-load-test:latest .
      #- docker tag php-load-test:latest 069554186194.dkr.ecr.ap-southeast-1.amazonaws.com/mywebsite:latest
      - ARTIFACT_NAME="myapp-$CODEBUILD_WEBHOOK_HEAD_REF.zip"
      - env
      - echo "Artifact name ${ARTIFACT_NAME}"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 069554186194.dkr.ecr.ap-southeast-1.amazonaws.com/mywebsite:latest
      #- aws s3 cp myapp.zip s3://my-bucket/$ARTIFACT_NAME
